apiVersion: ENC[AES256_GCM,data:5Ps=,iv:6LuPQYviiZnTAhK7XgEKjxYXn1Fxf36OsCA9cSiBR7M=,tag:vJzqiT4PISBqsjh9k0a2VA==,type:str]
kind: ENC[AES256_GCM,data:PWhTLnwx,iv:lIgPqDdfXjKQptWlGtBYgTQlTpbvLzEALaDsu4KQi/4=,tag:1gMN7+FNZVgHEg02csXqdg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IUC9oeammtMsHvOefMXkt3/kP+Q=,iv:1YjbdXh5w2k4bWfunojzTPZ4+YrRXKHj6bdH2Pu8yP0=,tag:ZaaHzZVzKWjHjU8YDxEaWA==,type:str]
    namespace: ENC[AES256_GCM,data:0rq0BQDi6YJWrGl0,iv:oeY2No5tBwVwlAxVyc9CoxWlwKl3FeR5EL843KXd1q0=,tag:6XeOd992Z+ceqqMbtUvmRg==,type:str]
type: ENC[AES256_GCM,data:0pCDllSN,iv:cTkjl8CUypDQjL00KoqJO2wba62+fjNCmH+pBfMOg+E=,tag:OOLFhr/0ZAzR90dg2zX2Pg==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:qlorWP5WLmKLgXgBp/OS6nfCoDxG72h+sriK4DyNMA==,iv:+gFpLp1CHgvESHxeqEauzYqVUEY45/vLxVrXqLZGkLU=,tag:jmAlcNgrJx4zW77n2ErH8w==,type:str]
sops:
    age:
        - recipient: age1aa2zdus8xp2gw5chrjk2c95ngvxxy0q44ga0rfcuwxnash7h5y5qzszjcv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalpLS0poTXVHYzRJMlo3
            am42bDFDQVJXYWpxVHE5RENNNmV3d2lQUTFVCjlVQk1TYUxVME4wS2JNcml2ZnZ4
            NUlzQnJHZmhabUhKOWQ3RjNnSDY4VlkKLS0tIEk4a1M2SEhNdmhEYnQxMlAraWV5
            NVhUR1h0RmU0dkI0ZFovdWV1THpDTDgKjuIhlx6FSFPGgWu7+d9xymnxPU2zPvpk
            yUX4DUtJSOFZSOvqJC/PsnPZlLJ3WvQl9tfweTHeg9qrTEvnSti+oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T19:26:13Z"
    mac: ENC[AES256_GCM,data:dyOkCB8UbB0bjtGgtrICLOfw17SQRTIKS8PQTuzf/k5Hrvu5sXqPa7NWS1Kh0phVCkFjrJlGlNKhaOrIR7TjjmvpC727OQss34BKAOGQQQP5Mz9YxpViyZvR1Ldr35hwv3vYaGIHGolMS2ZH6DNEwJrGyOYSyim3AKHOWQe1v9s=,iv:oHLJfEL99k6bpk+wXMNV9Nk2dSmL5fHlFXGq1bMhCiI=,tag:um+H1AvZY6ndm8fNywk7sA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
