apiVersion: ENC[AES256_GCM,data:7Zo=,iv:kV0ZWJfRveBuFTYi/cc1jBdAzWqJ/t6qkJ9164uTwg4=,tag:K7CsD3ZzdspPF5Uz4oRUHw==,type:str]
kind: ENC[AES256_GCM,data:kHzsRz8d,iv:G/Fn9v2NC7FLRX7Q8nLio4mS8LK7iXItRb2B3e7g0so=,tag:P9JlUDQn1Fek0oUxjp9aow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ItTaxKZiKnyQirQ=,iv:jww9bZKsOYZLBrBA6RxYgsOE5Wjeo8J2fM646BM3sqc=,tag:bEnyuPWGL2m0770GC3CqAQ==,type:str]
    namespace: ENC[AES256_GCM,data:EMLseZz6Kw==,iv:jHn4HsejR1rJtgNbazLtpZg3XV48z6e9pNO7cz13fv8=,tag:p87a3esJrNlXn1FUhKlhRg==,type:str]
type: ENC[AES256_GCM,data:YSYIA+ZQ,iv:Arib6O06NZTk3f/rR9RN9x2tCs0aORpM5dWApoiDsV8=,tag:G388u2e8w0dMewDcasOfSw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:6mlv4omMTtackigraFdcUaW3QkSVD8w=,iv:fHTSELtGhRBdUqJUdKyom4bvtfOvKAfv9yzLsKC2eS8=,tag:woXwKYoRzKsE4E7C0yLYew==,type:str]
    postgres-password: ENC[AES256_GCM,data:0AJQQoxdVsL1Oj2HitY78bDHrUwQTx65wvFj84U=,iv:TzbjDefc79C4Elbmgnu1hxrSFdqTbSYmijGuAX0KyG8=,tag:RfulowqxeHLWqED9P32D3A==,type:str]
sops:
    age:
        - recipient: age12pn8q6ewl6j5yyv3z9kqfa8y294kfmefxaxxzxfgt6xa6gwnpdhq5h2d7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcGFaUDlFY3RsMWNHaDNz
            RFlERytCa0dXdTE2OFgvUU9HNVB4UDl3MkdvCnBVekxDTnNON1RTdFhxNTJib0t4
            OTI3MVd1R0pMc05KNnZMUUJkaWJYK2MKLS0tIHdaM2ZGcXh1aWFvOFBBVW5iWEZE
            MndiUVgwdnEweUIvalNMK2ZoL01QYWcK5YCOYtXNDx8JY8Xr08d/fe+dXvem1yUM
            sds+7dph6v2bsrGpIeGT0KG6faB4axOXHXs7vHaFVyNW/yKxHQNJNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T19:26:13Z"
    mac: ENC[AES256_GCM,data:NNgwX2yvrP5tQAXVAUwNaSYVhkV50D4fAoZR6UaxlwtZNT0xhLhYlULS58G1i33FzFhMhxbIuu3scOf9MeK1YeBqrNcfbYlewiKNt8wbPAM1slI7OEyTzJFeT8BChcpaFBh119gRBlaO1jUxkFJCiEkRXAGuWr9Zo1DY8JIBC1A=,iv:Xpc+xPOb/o1TomHkZA2Tu5f1TvnvQzH9vTJocps7rYY=,tag:bFyKIpUEqX9eixrzoH+W9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
