name: automatic updates

on: pull_request

permissions:
  pull-requests: write
  contents: write
jobs:
  automatic-updates:
    uses: 99linesofcode/.github/.github/workflows/automatic-updates.yaml@main
